### PR TITLE
wip: add rand history addition

### PR DESCRIPTION
**Pull request by Moumouls**
Hi @herumi  so based on your comment https://github.com/herumi/she-wasm/issues/13#issuecomment-963129887

I think i can now try to implement some JS side stuff to accomplish my suggestion based on your work into the wasm:

```ts
const c1 = enc(1,r1)
const c2 = enc(0,r2)
const c3 = enc(1,r3)

const addedC = c1+c2+c3
const zkpEven = zkpOr(addedC, [r1,r2,r3], [0,2,4,6,8,10])
// We are now able to prove that addedC is even in 0,10
```

**Here my new first suggestion**

```ts
const r1, r2, r3
const m1 = 1
const m2 = 0
const m3 = 1

const mX = m1 + m2 + m3 // 2
const c1 = enc(m1,r1)
const c2 = enc(m2,r2)
const c3 = enc(m3,r3)

// Since enc(m1, r1) + enc(m2, r2) === enc(m1+m2, r1+r2)
// And when we execute enc(m1,r1) first element of r1 is always the randomValue used to compute C
// I would like to add the function to allow to add r1[0] + r2[0]
const rX = she.RandHistory.add(she.RandHistory.add(r1,r2),r3)

const addedC = she.add(she.add(c1,c2),c3)
const [newAddedC, Zkp] = zkpOr(mX, rX, [0,2,4,6,8,10])

// since rX === r1 + r2 + r3 and mX = m1 + m2 + m3
assert.equal(addedC.serialize(), newAddedC.serialize())
```

Here @herumi  i just need some help on the alloc step, you can check out my branch, I have not been able to retrieve the array of 32 bytes after _mclBnFr_add, i only have correct 8 values.

r1, r2 are arrays of 32 elements, RX seems to only contain 8 correct elements; next elements seems to not be part of the `_mclBnFr_add` computation 

Do you have an idea here ?

May be _mclBnFr_add is only capable to r1 + r2 on 8 elements.

### CODE REVIEW

**Comment by Moumouls** [comment]
Once rand history addition is supported i will be happy to add the ZKPSet JS implementation 🙂

**Comment by Moumouls** [comment]
Also @herumi  i tried to export the `encWithZkpSet` fn from cpp via ecc to use the function in JS, i'm not sure on how to do it correctly. If you have some suggestion 🙂 

I'm not sure on how to declare the `mVec` and how to alloc correctly the mVec from JS side.

**Comment by herumi** [comment]
I'll do that. Would you mind waiting a moment?

**Comment by Moumouls** [comment]
Yes no problem ☺️

**Comment by Moumouls** [comment]
Hi @herumi  if you have some suggestion about random history add via `_mclBnFr_add ` i'll be happy to help :) If you have a moment 👍

**Comment by herumi** [comment]
Thank you for the patch.
It has some problems, so I made another commit. https://github.com/herumi/she-wasm/commit/4e529ca4bd5dedd7bcd74bb39ba024d6994caba4

**Comment by herumi** [comment]
I was forced to push https://github.com/herumi/she-wasm/commit/789d02ac6cfec96d89c5073234bbcf6b3b20aa7d again to remove unnecessary diff.

**Comment by herumi** [comment]
I'll close this PR because the function is made.

**Pull request closed without merging**
