### PR TITLE
Use Jest (test parallism), Prettier, add verifyEq, ZkpBinEq and encWithZkpBinEq

### PR DESCRIPTION
**Pull request by Moumouls**

### CODE REVIEW

**Comment by herumi** [comment]
Thank you for the pull request. But it changes the format then the difference is too large.
Could you minimize the diff?

**Comment by Moumouls** [comment]
Indeed I should have done 2 distinct PRs, but sadly prettier addition was the first thing i added.
Sadly i think i can't reduce the diff but here you can search following functions:

In she.js
``` 
verifyEq
encWithZkpBinEq
ZkpBinEq
sheZkpBinEqSerialize
sheZkpBinEqDeserialize
```

In tests/helper.js
```
should handle zkp bin eq
zkpBinTestEqSub
```

I removed the travis ci to get advantage of github actions.

**Comment by Moumouls** [comment]
@herumi  you can check this particular commit: https://github.com/herumi/she-wasm/pull/2/commits/02b5bae0066173f08d47ab2038db9d903c6aef3a

**Comment by herumi** [comment]
Okay, I'll add those ZKP APIs.

**Comment by Moumouls** [comment]
@herumi  you don't want to merge this PR ?

**Comment by herumi** [comment]
To cherry-pick `Add Eq support ` conflicts, so I'll manually merge it.

**Comment by Moumouls** [comment]
i cehcked `Add Eq support ` commit is not complete and missing some methods
You do not want to add the Jest/Prettier/Github Action part ?

**Comment by herumi** [comment]
I do not check your patch in detail because the diff is too big.

**Comment by Moumouls** [comment]
okay let me know when i can merge master

**Pull request closed without merging**
